### K-Fold Cross Validation

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np

In [2]:
digits = load_digits()

In [3]:
from sklearn.model_selection import StratifiedKFold # Same as K fold but checks than all target can be feed

In [23]:
folds = StratifiedKFold(n_splits = 3)

In [5]:
from sklearn.model_selection import KFold

In [6]:
kf = KFold(n_splits = 3)

In [7]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [8]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='lbfgs', max_iter = 4000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 70), X_train, X_test, y_train, y_test))

In [9]:
scores_l

[0.9198664440734557, 0.9432387312186978, 0.9165275459098498]

In [10]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [11]:
scores_rf

[0.9298831385642737, 0.9482470784641068, 0.9348914858096828]

In [12]:
from sklearn.model_selection import cross_val_score

In [13]:
cross_val_score(LogisticRegression(solver='lbfgs', max_iter = 4000), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [14]:
cross_val_score(SVC(kernel = 'rbf'), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [15]:
cross_val_score(SVC(kernel = 'linear'), digits.data, digits.target)

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [16]:
cross_val_score(RandomForestClassifier(n_estimators = 50), digits.data, digits.target)

array([0.93333333, 0.9       , 0.95821727, 0.96100279, 0.93036212])